### ISSUE TITLE
cnpm i 之后， npm run dev:h5 报 js 错误，taro 全局安装的目前最新版 1.2.22

### ISSUE THREAD

**Issue by uncleAndyChen** [icai/taro-cnode#13]
监听文件修改中...

./.temp/hoc/router.js
Module build failed (from ./node_modules/_babel-loader@7.1.4@babel-loader/lib/index.js):
TypeError: C:/workspace/taro/taro-cnode/.temp/hoc/router.js: Property local of ExportSpecifier expected node to be of a type ["Identifier"] but instead got "MemberExpression"
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)

**Comment by uncleAndyChen** [comment]
补充：
$ node -v
v10.15.3

$ npm -v
6.9.0

**Comment by icai** [comment]
@uncleAndyChen 
你看看是源码报错还是框架报错，框架报错你去群问问老李
1.2.15 是没有问题 H5

**Comment by JustDo** [comment]
> 监听文件修改中...
> 
> ./.temp/hoc/router.js
> Module build failed (from ./node_modules/_babel-loader@7.1.4@babel-loader/lib/index.js):
> TypeError: C:/workspace/taro/taro-cnode/.temp/hoc/router.js: Property local of ExportSpecifier expected node to be of a type ["Identifier"] but instead got "MemberExpression"
> at Array.forEach ()
> at Array.forEach ()

遇到同样问题，不知道你解决了么

**Comment by icai** [comment]
@JustDo 应该新版语法有所修改导致的，我今晚看看
